package com.zens.unify.entity;

public class Camera {
	
	private String regionName;
	
	private String cnName;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_camera.ID
     *
     * @mbggenerated Tue Sep 02 18:00:35 CST 2014
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_camera.FName
     *
     * @mbggenerated Tue Sep 02 18:00:35 CST 2014
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_camera.FUrl
     *
     * @mbggenerated Tue Sep 02 18:00:35 CST 2014
     */
    private String url;

    public String getCnName() {
		return cnName;
	}

	public void setCnName(String cnName) {
		this.cnName = cnName;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_camera.FImg
     *
     * @mbggenerated Tue Sep 02 18:00:35 CST 2014
     */
    private String img;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_camera.FExpand
     *
     * @mbggenerated Tue Sep 02 18:00:35 CST 2014
     */
    private String expand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_camera.FRegionsId
     *
     * @mbggenerated Tue Sep 02 18:00:35 CST 2014
     */
    private Long regionsId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_camera.ID
     *
     * @return the value of t_camera.ID
     *
     * @mbggenerated Tue Sep 02 18:00:35 CST 2014
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_camera.ID
     *
     * @param id the value for t_camera.ID
     *
     * @mbggenerated Tue Sep 02 18:00:35 CST 2014
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_camera.FName
     *
     * @return the value of t_camera.FName
     *
     * @mbggenerated Tue Sep 02 18:00:35 CST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_camera.FName
     *
     * @param name the value for t_camera.FName
     *
     * @mbggenerated Tue Sep 02 18:00:35 CST 2014
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_camera.FUrl
     *
     * @return the value of t_camera.FUrl
     *
     * @mbggenerated Tue Sep 02 18:00:35 CST 2014
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_camera.FUrl
     *
     * @param url the value for t_camera.FUrl
     *
     * @mbggenerated Tue Sep 02 18:00:35 CST 2014
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_camera.FImg
     *
     * @return the value of t_camera.FImg
     *
     * @mbggenerated Tue Sep 02 18:00:35 CST 2014
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_camera.FImg
     *
     * @param img the value for t_camera.FImg
     *
     * @mbggenerated Tue Sep 02 18:00:35 CST 2014
     */
    public void setImg(String img) {
        this.img = img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_camera.FExpand
     *
     * @return the value of t_camera.FExpand
     *
     * @mbggenerated Tue Sep 02 18:00:35 CST 2014
     */
    public String getExpand() {
        return expand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_camera.FExpand
     *
     * @param expand the value for t_camera.FExpand
     *
     * @mbggenerated Tue Sep 02 18:00:35 CST 2014
     */
    public void setExpand(String expand) {
        this.expand = expand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_camera.FRegionsId
     *
     * @return the value of t_camera.FRegionsId
     *
     * @mbggenerated Tue Sep 02 18:00:35 CST 2014
     */
    public Long getRegionsId() {
        return regionsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_camera.FRegionsId
     *
     * @param regionsId the value for t_camera.FRegionsId
     *
     * @mbggenerated Tue Sep 02 18:00:35 CST 2014
     */
    public void setRegionsId(Long regionsId) {
        this.regionsId = regionsId;
    }

	public String getRegionName() {
		return regionName;
	}

	public void setRegionName(String regionName) {
		this.regionName = regionName;
	}
}