package com.zens.unify.entity;

import java.util.ArrayList;
import java.util.List;

public class DataExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_data
     *
     * @mbggenerated Wed Jul 16 11:37:55 CST 2014
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_data
     *
     * @mbggenerated Wed Jul 16 11:37:55 CST 2014
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_data
     *
     * @mbggenerated Wed Jul 16 11:37:55 CST 2014
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data
     *
     * @mbggenerated Wed Jul 16 11:37:55 CST 2014
     */
    public DataExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data
     *
     * @mbggenerated Wed Jul 16 11:37:55 CST 2014
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data
     *
     * @mbggenerated Wed Jul 16 11:37:55 CST 2014
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data
     *
     * @mbggenerated Wed Jul 16 11:37:55 CST 2014
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data
     *
     * @mbggenerated Wed Jul 16 11:37:55 CST 2014
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data
     *
     * @mbggenerated Wed Jul 16 11:37:55 CST 2014
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data
     *
     * @mbggenerated Wed Jul 16 11:37:55 CST 2014
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data
     *
     * @mbggenerated Wed Jul 16 11:37:55 CST 2014
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data
     *
     * @mbggenerated Wed Jul 16 11:37:55 CST 2014
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data
     *
     * @mbggenerated Wed Jul 16 11:37:55 CST 2014
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data
     *
     * @mbggenerated Wed Jul 16 11:37:55 CST 2014
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_data
     *
     * @mbggenerated Wed Jul 16 11:37:55 CST 2014
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andFtaskconfigidIsNull() {
            addCriterion("FTaskConfigId is null");
            return (Criteria) this;
        }

        public Criteria andFtaskconfigidIsNotNull() {
            addCriterion("FTaskConfigId is not null");
            return (Criteria) this;
        }

        public Criteria andFtaskconfigidEqualTo(Long value) {
            addCriterion("FTaskConfigId =", value, "taskConfigId");
            return (Criteria) this;
        }

        public Criteria andFtaskconfigidNotEqualTo(Long value) {
            addCriterion("FTaskConfigId <>", value, "taskConfigId");
            return (Criteria) this;
        }

        public Criteria andFtaskconfigidGreaterThan(Long value) {
            addCriterion("FTaskConfigId >", value, "taskConfigId");
            return (Criteria) this;
        }

        public Criteria andFtaskconfigidGreaterThanOrEqualTo(Long value) {
            addCriterion("FTaskConfigId >=", value, "taskConfigId");
            return (Criteria) this;
        }

        public Criteria andFtaskconfigidLessThan(Long value) {
            addCriterion("FTaskConfigId <", value, "taskConfigId");
            return (Criteria) this;
        }

        public Criteria andFtaskconfigidLessThanOrEqualTo(Long value) {
            addCriterion("FTaskConfigId <=", value, "taskConfigId");
            return (Criteria) this;
        }

        public Criteria andFtaskconfigidIn(List<Long> values) {
            addCriterion("FTaskConfigId in", values, "taskConfigId");
            return (Criteria) this;
        }

        public Criteria andFtaskconfigidNotIn(List<Long> values) {
            addCriterion("FTaskConfigId not in", values, "taskConfigId");
            return (Criteria) this;
        }

        public Criteria andFtaskconfigidBetween(Long value1, Long value2) {
            addCriterion("FTaskConfigId between", value1, value2, "taskConfigId");
            return (Criteria) this;
        }

        public Criteria andFtaskconfigidNotBetween(Long value1, Long value2) {
            addCriterion("FTaskConfigId not between", value1, value2, "taskConfigId");
            return (Criteria) this;
        }

        public Criteria andFdataIsNull() {
            addCriterion("FData is null");
            return (Criteria) this;
        }

        public Criteria andFdataIsNotNull() {
            addCriterion("FData is not null");
            return (Criteria) this;
        }

        public Criteria andFdataEqualTo(String value) {
            addCriterion("FData =", value, "data");
            return (Criteria) this;
        }

        public Criteria andFdataNotEqualTo(String value) {
            addCriterion("FData <>", value, "data");
            return (Criteria) this;
        }

        public Criteria andFdataGreaterThan(String value) {
            addCriterion("FData >", value, "data");
            return (Criteria) this;
        }

        public Criteria andFdataGreaterThanOrEqualTo(String value) {
            addCriterion("FData >=", value, "data");
            return (Criteria) this;
        }

        public Criteria andFdataLessThan(String value) {
            addCriterion("FData <", value, "data");
            return (Criteria) this;
        }

        public Criteria andFdataLessThanOrEqualTo(String value) {
            addCriterion("FData <=", value, "data");
            return (Criteria) this;
        }

        public Criteria andFdataLike(String value) {
            addCriterion("FData like", value, "data");
            return (Criteria) this;
        }

        public Criteria andFdataNotLike(String value) {
            addCriterion("FData not like", value, "data");
            return (Criteria) this;
        }

        public Criteria andFdataIn(List<String> values) {
            addCriterion("FData in", values, "data");
            return (Criteria) this;
        }

        public Criteria andFdataNotIn(List<String> values) {
            addCriterion("FData not in", values, "data");
            return (Criteria) this;
        }

        public Criteria andFdataBetween(String value1, String value2) {
            addCriterion("FData between", value1, value2, "data");
            return (Criteria) this;
        }

        public Criteria andFdataNotBetween(String value1, String value2) {
            addCriterion("FData not between", value1, value2, "data");
            return (Criteria) this;
        }

        public Criteria andFupdateipIsNull() {
            addCriterion("FUpdateIp is null");
            return (Criteria) this;
        }

        public Criteria andFupdateipIsNotNull() {
            addCriterion("FUpdateIp is not null");
            return (Criteria) this;
        }

        public Criteria andFupdateipEqualTo(String value) {
            addCriterion("FUpdateIp =", value, "updateIp");
            return (Criteria) this;
        }

        public Criteria andFupdateipNotEqualTo(String value) {
            addCriterion("FUpdateIp <>", value, "updateIp");
            return (Criteria) this;
        }

        public Criteria andFupdateipGreaterThan(String value) {
            addCriterion("FUpdateIp >", value, "updateIp");
            return (Criteria) this;
        }

        public Criteria andFupdateipGreaterThanOrEqualTo(String value) {
            addCriterion("FUpdateIp >=", value, "updateIp");
            return (Criteria) this;
        }

        public Criteria andFupdateipLessThan(String value) {
            addCriterion("FUpdateIp <", value, "updateIp");
            return (Criteria) this;
        }

        public Criteria andFupdateipLessThanOrEqualTo(String value) {
            addCriterion("FUpdateIp <=", value, "updateIp");
            return (Criteria) this;
        }

        public Criteria andFupdateipLike(String value) {
            addCriterion("FUpdateIp like", value, "updateIp");
            return (Criteria) this;
        }

        public Criteria andFupdateipNotLike(String value) {
            addCriterion("FUpdateIp not like", value, "updateIp");
            return (Criteria) this;
        }

        public Criteria andFupdateipIn(List<String> values) {
            addCriterion("FUpdateIp in", values, "updateIp");
            return (Criteria) this;
        }

        public Criteria andFupdateipNotIn(List<String> values) {
            addCriterion("FUpdateIp not in", values, "updateIp");
            return (Criteria) this;
        }

        public Criteria andFupdateipBetween(String value1, String value2) {
            addCriterion("FUpdateIp between", value1, value2, "updateIp");
            return (Criteria) this;
        }

        public Criteria andFupdateipNotBetween(String value1, String value2) {
            addCriterion("FUpdateIp not between", value1, value2, "updateIp");
            return (Criteria) this;
        }

        public Criteria andFupdatetimeIsNull() {
            addCriterion("FUpdateTime is null");
            return (Criteria) this;
        }

        public Criteria andFupdatetimeIsNotNull() {
            addCriterion("FUpdateTime is not null");
            return (Criteria) this;
        }

        public Criteria andFupdatetimeEqualTo(String value) {
            addCriterion("FUpdateTime =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andFupdatetimeNotEqualTo(String value) {
            addCriterion("FUpdateTime <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andFupdatetimeGreaterThan(String value) {
            addCriterion("FUpdateTime >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andFupdatetimeGreaterThanOrEqualTo(String value) {
            addCriterion("FUpdateTime >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andFupdatetimeLessThan(String value) {
            addCriterion("FUpdateTime <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andFupdatetimeLessThanOrEqualTo(String value) {
            addCriterion("FUpdateTime <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andFupdatetimeLike(String value) {
            addCriterion("FUpdateTime like", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andFupdatetimeNotLike(String value) {
            addCriterion("FUpdateTime not like", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andFupdatetimeIn(List<String> values) {
            addCriterion("FUpdateTime in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andFupdatetimeNotIn(List<String> values) {
            addCriterion("FUpdateTime not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andFupdatetimeBetween(String value1, String value2) {
            addCriterion("FUpdateTime between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andFupdatetimeNotBetween(String value1, String value2) {
            addCriterion("FUpdateTime not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andFcityIsNull() {
            addCriterion("FCity is null");
            return (Criteria) this;
        }

        public Criteria andFcityIsNotNull() {
            addCriterion("FCity is not null");
            return (Criteria) this;
        }

        public Criteria andFcityEqualTo(String value) {
            addCriterion("FCity =", value, "city");
            return (Criteria) this;
        }

        public Criteria andFcityNotEqualTo(String value) {
            addCriterion("FCity <>", value, "city");
            return (Criteria) this;
        }

        public Criteria andFcityGreaterThan(String value) {
            addCriterion("FCity >", value, "city");
            return (Criteria) this;
        }

        public Criteria andFcityGreaterThanOrEqualTo(String value) {
            addCriterion("FCity >=", value, "city");
            return (Criteria) this;
        }

        public Criteria andFcityLessThan(String value) {
            addCriterion("FCity <", value, "city");
            return (Criteria) this;
        }

        public Criteria andFcityLessThanOrEqualTo(String value) {
            addCriterion("FCity <=", value, "city");
            return (Criteria) this;
        }

        public Criteria andFcityLike(String value) {
            addCriterion("FCity like", value, "city");
            return (Criteria) this;
        }

        public Criteria andFcityNotLike(String value) {
            addCriterion("FCity not like", value, "city");
            return (Criteria) this;
        }

        public Criteria andFcityIn(List<String> values) {
            addCriterion("FCity in", values, "city");
            return (Criteria) this;
        }

        public Criteria andFcityNotIn(List<String> values) {
            addCriterion("FCity not in", values, "city");
            return (Criteria) this;
        }

        public Criteria andFcityBetween(String value1, String value2) {
            addCriterion("FCity between", value1, value2, "city");
            return (Criteria) this;
        }

        public Criteria andFcityNotBetween(String value1, String value2) {
            addCriterion("FCity not between", value1, value2, "city");
            return (Criteria) this;
        }

        public Criteria andFexpandIsNull() {
            addCriterion("FExpand is null");
            return (Criteria) this;
        }

        public Criteria andFexpandIsNotNull() {
            addCriterion("FExpand is not null");
            return (Criteria) this;
        }

        public Criteria andFexpandEqualTo(String value) {
            addCriterion("FExpand =", value, "expand");
            return (Criteria) this;
        }

        public Criteria andFexpandNotEqualTo(String value) {
            addCriterion("FExpand <>", value, "expand");
            return (Criteria) this;
        }

        public Criteria andFexpandGreaterThan(String value) {
            addCriterion("FExpand >", value, "expand");
            return (Criteria) this;
        }

        public Criteria andFexpandGreaterThanOrEqualTo(String value) {
            addCriterion("FExpand >=", value, "expand");
            return (Criteria) this;
        }

        public Criteria andFexpandLessThan(String value) {
            addCriterion("FExpand <", value, "expand");
            return (Criteria) this;
        }

        public Criteria andFexpandLessThanOrEqualTo(String value) {
            addCriterion("FExpand <=", value, "expand");
            return (Criteria) this;
        }

        public Criteria andFexpandLike(String value) {
            addCriterion("FExpand like", value, "expand");
            return (Criteria) this;
        }

        public Criteria andFexpandNotLike(String value) {
            addCriterion("FExpand not like", value, "expand");
            return (Criteria) this;
        }

        public Criteria andFexpandIn(List<String> values) {
            addCriterion("FExpand in", values, "expand");
            return (Criteria) this;
        }

        public Criteria andFexpandNotIn(List<String> values) {
            addCriterion("FExpand not in", values, "expand");
            return (Criteria) this;
        }

        public Criteria andFexpandBetween(String value1, String value2) {
            addCriterion("FExpand between", value1, value2, "expand");
            return (Criteria) this;
        }

        public Criteria andFexpandNotBetween(String value1, String value2) {
            addCriterion("FExpand not between", value1, value2, "expand");
            return (Criteria) this;
        }

        public Criteria andFbackupdataIsNull() {
            addCriterion("FBackupData is null");
            return (Criteria) this;
        }

        public Criteria andFbackupdataIsNotNull() {
            addCriterion("FBackupData is not null");
            return (Criteria) this;
        }

        public Criteria andFbackupdataEqualTo(String value) {
            addCriterion("FBackupData =", value, "backupData");
            return (Criteria) this;
        }

        public Criteria andFbackupdataNotEqualTo(String value) {
            addCriterion("FBackupData <>", value, "backupData");
            return (Criteria) this;
        }

        public Criteria andFbackupdataGreaterThan(String value) {
            addCriterion("FBackupData >", value, "backupData");
            return (Criteria) this;
        }

        public Criteria andFbackupdataGreaterThanOrEqualTo(String value) {
            addCriterion("FBackupData >=", value, "backupData");
            return (Criteria) this;
        }

        public Criteria andFbackupdataLessThan(String value) {
            addCriterion("FBackupData <", value, "backupData");
            return (Criteria) this;
        }

        public Criteria andFbackupdataLessThanOrEqualTo(String value) {
            addCriterion("FBackupData <=", value, "backupData");
            return (Criteria) this;
        }

        public Criteria andFbackupdataLike(String value) {
            addCriterion("FBackupData like", value, "backupData");
            return (Criteria) this;
        }

        public Criteria andFbackupdataNotLike(String value) {
            addCriterion("FBackupData not like", value, "backupData");
            return (Criteria) this;
        }

        public Criteria andFbackupdataIn(List<String> values) {
            addCriterion("FBackupData in", values, "backupData");
            return (Criteria) this;
        }

        public Criteria andFbackupdataNotIn(List<String> values) {
            addCriterion("FBackupData not in", values, "backupData");
            return (Criteria) this;
        }

        public Criteria andFbackupdataBetween(String value1, String value2) {
            addCriterion("FBackupData between", value1, value2, "backupData");
            return (Criteria) this;
        }

        public Criteria andFbackupdataNotBetween(String value1, String value2) {
            addCriterion("FBackupData not between", value1, value2, "backupData");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_data
     *
     * @mbggenerated do_not_delete_during_merge Wed Jul 16 11:37:55 CST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_data
     *
     * @mbggenerated Wed Jul 16 11:37:55 CST 2014
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}