package com.zens.unify.entity;

public class Regions {
	
	private String parentRegionsName;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_regions.ID
     *
     * @mbggenerated Tue Sep 02 11:00:25 CST 2014
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_regions.UUID
     *
     * @mbggenerated Tue Sep 02 11:00:25 CST 2014
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_regions.FName
     *
     * @mbggenerated Tue Sep 02 11:00:25 CST 2014
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_regions.FParentRegionsId
     *
     * @mbggenerated Tue Sep 02 11:00:25 CST 2014
     */
    private Long parentRegionsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_regions.FCnName
     *
     * @mbggenerated Tue Sep 02 11:00:25 CST 2014
     */
    private String cnName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_regions.FExpand
     *
     * @mbggenerated Tue Sep 02 11:00:25 CST 2014
     */
    private String expand;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_regions.ID
     *
     * @return the value of t_regions.ID
     *
     * @mbggenerated Tue Sep 02 11:00:25 CST 2014
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_regions.ID
     *
     * @param id the value for t_regions.ID
     *
     * @mbggenerated Tue Sep 02 11:00:25 CST 2014
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_regions.UUID
     *
     * @return the value of t_regions.UUID
     *
     * @mbggenerated Tue Sep 02 11:00:25 CST 2014
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_regions.UUID
     *
     * @param uuid the value for t_regions.UUID
     *
     * @mbggenerated Tue Sep 02 11:00:25 CST 2014
     */
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_regions.FName
     *
     * @return the value of t_regions.FName
     *
     * @mbggenerated Tue Sep 02 11:00:25 CST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_regions.FName
     *
     * @param fname the value for t_regions.FName
     *
     * @mbggenerated Tue Sep 02 11:00:25 CST 2014
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_regions.FParentRegionsId
     *
     * @return the value of t_regions.FParentRegionsId
     *
     * @mbggenerated Tue Sep 02 11:00:25 CST 2014
     */
    public Long getParentRegionsId() {
        return parentRegionsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_regions.FParentRegionsId
     *
     * @param fparentregionsid the value for t_regions.FParentRegionsId
     *
     * @mbggenerated Tue Sep 02 11:00:25 CST 2014
     */
    public void setParentRegionsId(Long fparentregionsid) {
        this.parentRegionsId = fparentregionsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_regions.FCnName
     *
     * @return the value of t_regions.FCnName
     *
     * @mbggenerated Tue Sep 02 11:00:25 CST 2014
     */
    public String getCnName() {
        return cnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_regions.FCnName
     *
     * @param cnName the value for t_regions.FCnName
     *
     * @mbggenerated Tue Sep 02 11:00:25 CST 2014
     */
    public void setCnName(String cnName) {
        this.cnName = cnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_regions.FExpand
     *
     * @return the value of t_regions.FExpand
     *
     * @mbggenerated Tue Sep 02 11:00:25 CST 2014
     */
    public String getExpand() {
        return expand;
    }

	public String getParentRegionsName() {
		return parentRegionsName;
	}

	public void setParentRegionsName(String parentRegionsName) {
		this.parentRegionsName = parentRegionsName;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_regions.FExpand
     *
     * @param expand the value for t_regions.FExpand
     *
     * @mbggenerated Tue Sep 02 11:00:25 CST 2014
     */
    public void setExpand(String expand) {
        this.expand = expand;
    }
}