package com.zens.unify.mapper;

import com.zens.unify.entity.Camera;
import com.zens.unify.entity.CameraExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CameraMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_camera
     *
     * @mbggenerated Tue Sep 02 18:00:35 CST 2014
     */
    int countByExample(CameraExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_camera
     *
     * @mbggenerated Tue Sep 02 18:00:35 CST 2014
     */
    int deleteByExample(CameraExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_camera
     *
     * @mbggenerated Tue Sep 02 18:00:35 CST 2014
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_camera
     *
     * @mbggenerated Tue Sep 02 18:00:35 CST 2014
     */
    int insert(Camera record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_camera
     *
     * @mbggenerated Tue Sep 02 18:00:35 CST 2014
     */
    int insertSelective(Camera record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_camera
     *
     * @mbggenerated Tue Sep 02 18:00:35 CST 2014
     */
    List<Camera> selectByExample(CameraExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_camera
     *
     * @mbggenerated Tue Sep 02 18:00:35 CST 2014
     */
    Camera selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_camera
     *
     * @mbggenerated Tue Sep 02 18:00:35 CST 2014
     */
    int updateByExampleSelective(@Param("record") Camera record, @Param("example") CameraExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_camera
     *
     * @mbggenerated Tue Sep 02 18:00:35 CST 2014
     */
    int updateByExample(@Param("record") Camera record, @Param("example") CameraExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_camera
     *
     * @mbggenerated Tue Sep 02 18:00:35 CST 2014
     */
    int updateByPrimaryKeySelective(Camera record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_camera
     *
     * @mbggenerated Tue Sep 02 18:00:35 CST 2014
     */
    int updateByPrimaryKey(Camera record);
}