package com.zens.unify.mapper;

import com.zens.unify.entity.Data;
import com.zens.unify.entity.DataExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data
     *
     * @mbggenerated Wed Jul 16 11:37:55 CST 2014
     */
    int countByExample(DataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data
     *
     * @mbggenerated Wed Jul 16 11:37:55 CST 2014
     */
    int deleteByExample(DataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data
     *
     * @mbggenerated Wed Jul 16 11:37:55 CST 2014
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data
     *
     * @mbggenerated Wed Jul 16 11:37:55 CST 2014
     */
    int insert(Data record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data
     *
     * @mbggenerated Wed Jul 16 11:37:55 CST 2014
     */
    int insertSelective(Data record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data
     *
     * @mbggenerated Wed Jul 16 11:37:55 CST 2014
     */
    List<Data> selectByExample(DataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data
     *
     * @mbggenerated Wed Jul 16 11:37:55 CST 2014
     */
    Data selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data
     *
     * @mbggenerated Wed Jul 16 11:37:55 CST 2014
     */
    int updateByExampleSelective(@Param("record") Data record, @Param("example") DataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data
     *
     * @mbggenerated Wed Jul 16 11:37:55 CST 2014
     */
    int updateByExample(@Param("record") Data record, @Param("example") DataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data
     *
     * @mbggenerated Wed Jul 16 11:37:55 CST 2014
     */
    int updateByPrimaryKeySelective(Data record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_data
     *
     * @mbggenerated Wed Jul 16 11:37:55 CST 2014
     */
    int updateByPrimaryKey(Data record);
    
    /**
     * 根据
     * @param taskConfigId
     * @return
     */
    Data getDataByTaskConfigId(@Param("taskConfigId") Long taskConfigId);
}