package com.zens.unify.mapper;

import com.zens.unify.entity.Menu;
import com.zens.unify.entity.MenuExample;
import org.apache.ibatis.annotations.Param;

public interface MenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_camera
     *
     * @mbggenerated Tue Sep 02 18:00:35 CST 2014
     */
    int deleteByExample(MenuExample example);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_camera
     *
     * @mbggenerated Tue Sep 02 18:00:35 CST 2014
     */
    int insertSelective(Menu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_camera
     *
     * @mbggenerated Tue Sep 02 18:00:35 CST 2014
     */
    Menu selectByExample(Menu t);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_camera
     *
     * @mbggenerated Tue Sep 02 18:00:35 CST 2014
     */
    int updateByExampleSelective(@Param("record") Menu record, @Param("example") MenuExample example);

}