package com.zens.unify.mapper;

import com.zens.unify.entity.Regions;
import com.zens.unify.entity.RegionsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RegionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_regions
     *
     * @mbggenerated Tue Sep 02 11:00:25 CST 2014
     */
    int countByExample(RegionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_regions
     *
     * @mbggenerated Tue Sep 02 11:00:25 CST 2014
     */
    int deleteByExample(RegionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_regions
     *
     * @mbggenerated Tue Sep 02 11:00:25 CST 2014
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_regions
     *
     * @mbggenerated Tue Sep 02 11:00:25 CST 2014
     */
    int insert(Regions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_regions
     *
     * @mbggenerated Tue Sep 02 11:00:25 CST 2014
     */
    int insertSelective(Regions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_regions
     *
     * @mbggenerated Tue Sep 02 11:00:25 CST 2014
     */
    List<Regions> selectByExample(RegionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_regions
     *
     * @mbggenerated Tue Sep 02 11:00:25 CST 2014
     */
    Regions selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_regions
     *
     * @mbggenerated Tue Sep 02 11:00:25 CST 2014
     */
    int updateByExampleSelective(@Param("record") Regions record, @Param("example") RegionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_regions
     *
     * @mbggenerated Tue Sep 02 11:00:25 CST 2014
     */
    int updateByExample(@Param("record") Regions record, @Param("example") RegionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_regions
     *
     * @mbggenerated Tue Sep 02 11:00:25 CST 2014
     */
    int updateByPrimaryKeySelective(Regions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_regions
     *
     * @mbggenerated Tue Sep 02 11:00:25 CST 2014
     */
    int updateByPrimaryKey(Regions record);
}