package com.zens.unify.mapper;

import com.zens.unify.entity.TaskConfig;
import com.zens.unify.entity.TaskConfigExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TaskConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_config
     *
     * @mbggenerated Wed Jul 16 11:37:55 CST 2014
     */
    int countByExample(TaskConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_config
     *
     * @mbggenerated Wed Jul 16 11:37:55 CST 2014
     */
    int deleteByExample(TaskConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_config
     *
     * @mbggenerated Wed Jul 16 11:37:55 CST 2014
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_config
     *
     * @mbggenerated Wed Jul 16 11:37:55 CST 2014
     */
    int insert(TaskConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_config
     *
     * @mbggenerated Wed Jul 16 11:37:55 CST 2014
     */
    int insertSelective(TaskConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_config
     *
     * @mbggenerated Wed Jul 16 11:37:55 CST 2014
     */
    List<TaskConfig> selectByExample(TaskConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_config
     *
     * @mbggenerated Wed Jul 16 11:37:55 CST 2014
     */
    TaskConfig selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_config
     *
     * @mbggenerated Wed Jul 16 11:37:55 CST 2014
     */
    int updateByExampleSelective(@Param("record") TaskConfig record, @Param("example") TaskConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_config
     *
     * @mbggenerated Wed Jul 16 11:37:55 CST 2014
     */
    int updateByExample(@Param("record") TaskConfig record, @Param("example") TaskConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_config
     *
     * @mbggenerated Wed Jul 16 11:37:55 CST 2014
     */
    int updateByPrimaryKeySelective(TaskConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_config
     *
     * @mbggenerated Wed Jul 16 11:37:55 CST 2014
     */
    int updateByPrimaryKey(TaskConfig record);
}